### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by masterdezign** [cvogt/2020-07-01-haskell-game-demo#1]
Hi!

I had a trouble to build the package. Resolved with installing `sdl2_mixer` via OS package manager.

I suggest you to include the dependencies in the README.

**Comment by cvogt** [comment]
thanks, added a note at the top of the readme. If you tried it or are playing with it, let me know what you think :)

**Comment by masterdezign** [comment]
> thanks, added a note at the top of the readme. If you tried it or are playing with it, let me know what you think :)

I haven't much time to play with it (yet). But due to some reason the graphic is not displayed when
running `stack exec live-coding-demo`, whereas in `stack exec shoot-em-up` the graphic shows up as expected.

**Comment by symbiont-chris-vogt** [comment]
Right `stack exec live-coding-demo` is what the talk started with, not how it ended. I admit that's confusing. shoot-em-up is similar to what we ended with
